
compile:
	javac $(wildcard src/*.java)

runnear:
	java -cp ./src/ NearestInsertion mona-100k.txt

runsmall:
	java -cp ./src/ SmallestInsertion mona-100k.txt

test:
	java -cp ./src/ Test

clean:
	rm -f ./src/*.class
