
compile:
	javac $(wildcard src/*.java)

runnear:
	java -cp ./src/ NearestInsertion tsp10.txt

runsmall:
	java -cp ./src/ SmallestInsertion tsp10.txt

test:
	java -cp ./src/ Test

clean:
	rm -f ./src/*.class
